### ISSUE TITLE
Create Customer Registration Endpoint

### ISSUE THREAD

**Issue by KennedyUC** [awsnigeriadevops/bank-server#1]
Create an endpoint for customer registration

**Comment by KennedyUC** [comment]
## User Story
An admin user should be able to create an account for a new customer

## Customer Information
- email 
- first_name
- last_name
- date_of_birth
- phone_number
- address
- account_type

## Tasks
- [ ] Implement the endpoint to handle customer registration requests in the `../bank_app/servers/authentication` dir.
- [ ] Implement the necessary logic to process incoming customer registration data in the `../bank_app/servers/authentication` dir.
- [ ] Define the data model (schema) for the customer registration in the `../bank_app/db/models/authentication` dir.
- [ ] Implement the SQL queries for creating a new customer record in the database in the `../bank_app/db/repositories/authentication` dir.
- [ ] Add any environment variable to the `../bank_app/core/config.py` file.
