### ISSUE TITLE
Create Admin Registration Endpoint

### ISSUE THREAD

**Issue by KennedyUC** [awsnigeriadevops/bank-server#10]
Create an endpoint for admin registration

**Comment by KennedyUC** [comment]
## User Story
The admin should be able to register a new account

## Admin User Information
- username
- password
- email 
- first_name
- last_name
- phone_number

## Tasks
- [ ] Implement an endpoint to handle admin registration requests to the `../bank_app/servers/authentication` dir.
- [ ] Implement the necessary logic to process incoming registration data to the `../bank_app/servers/authentication` dir.
- [ ] Define the data model to store user information stated above to the `../bank_app/db/models/authentication` dir.
- [ ] Implement the SQL queries for creating a new admin record in the database to the `../bank_app/db/repositories/authentication` dir.
- [ ] Add any environment variable to the `../bank_app/core/config.py` file.
