### ISSUE TITLE
Create Admin Login Endpoint

### ISSUE THREAD

**Issue by KennedyUC** [awsnigeriadevops/bank-server#11]
Create the endpoint for admin user login

**Comment by KennedyUC** [comment]
## User Story
An admin user should be able to login to the admin page with email and password

## Login Information
- email
- password

## Tasks
- [ ] Implement an endpoint to handle admin login requests to the `../bank_app/servers/authentication` dir.
- [ ] Define the data model for the login information stated above to the `../bank_app/db/models/authentication` dir.
- [ ] Add any environment variable to the `../bank_app/core/config.py` file.
