### ISSUE TITLE
Create endpoint for viewing all admin profiles

### ISSUE THREAD

**Issue by KennedyUC** [awsnigeriadevops/bank-server#12]
Create an endpoint for the super_admin to get all the admin profiles

**Comment by KennedyUC** [comment]
## User Story
The super_admin should be able to get all the admin profiles

## Tasks
- [ ] Implement an endpoint to handle get admin requests to the `../bank_app/servers/authentication` dir.
- [ ] Implement the queries and logic to get all admin records from the db to the `../bank_app/db/../authentication` dir.
- [ ] Add any environment variable to the `../bank_app/core/config.py` file.
