### ISSUE TITLE
Create endpoint for viewing admin profile by admin_id

### ISSUE THREAD

**Issue by KennedyUC** [awsnigeriadevops/bank-server#13]
Create an endpoint for an admin to get his/her profile

**Comment by KennedyUC** [comment]
## Tasks
- [ ] Implement an endpoint to handle get admin by id requests to the `../bank_app/servers/authentication` dir.
- [ ] Implement the queries and logic to get admin by id records from the db to the `../bank_app/db/../authentication` dir.
- [ ] Add any environment variable to the `../bank_app/core/config.py` file.
