### ISSUE TITLE
Create endpoint for viewing admin profile by email

### ISSUE THREAD

**Issue by KennedyUC** [awsnigeriadevops/bank-server#14]
Create an endpoint to get admin profile by email

**Comment by KennedyUC** [comment]
## Tasks
- [ ] Implement an endpoint to handle get admin by email requests to the `../bank_app/servers/authentication` dir.
- [ ] Implement the queries and logic to get admin by email record from the db to the `../bank_app/db/../authentication` dir.
- [ ] Add any environment variable to the `../bank_app/core/config.py` file.
