### ISSUE TITLE
Create endpoint for updating admin profile

### ISSUE THREAD

**Issue by KennedyUC** [awsnigeriadevops/bank-server#15]
Create an endpoint for updating the profile of an admin

**Comment by KennedyUC** [comment]
## User Story
The admin should be able to update certain profile details

## Details to be updated
- phone number
- password

## Tasks
- [ ] Implement an endpoint to handle admin profile update requests to the `../bank_app/servers/authentication` dir.
- [ ] Implement the queries and logic to update admin profile records in the db to the `../bank_app/db/../authentication` dir.
- [ ] Add any environment variable to the `../bank_app/core/config.py` file.
