### ISSUE TITLE
Create endpoint for deleting admin profile

### ISSUE THREAD

**Issue by KennedyUC** [awsnigeriadevops/bank-server#16]
Create an endpoint for a super_admin to delete an admin profile

**Comment by KennedyUC** [comment]
## User Story
The super_admin should be able to delete an admin profile record in case the admin leaves the bank.

## Tasks
- [ ] Implement an endpoint to handle delete admin profile record requests to the `../bank_app/servers/authentication` dir.
- [ ] Implement the queries and logic to delete an admin record from the db to the `../bank_app/db/../authentication` dir.
- [ ] Add any environment variable to the `../bank_app/core/config.py` file.
