### ISSUE TITLE
Create endpoint for viewing customer profile by account_number

### ISSUE THREAD

**Issue by KennedyUC** [awsnigeriadevops/bank-server#17]
Create an endpoint to get the customer's profile by account_number

**Comment by KennedyUC** [comment]
## User Story
The customer profile should be able to be retrieved using the customer's account number

## Tasks
- [ ] Implement an endpoint to handle the API requests to the `../bank_app/servers/authentication` dir.
- [ ] Implement the queries and logic to get the records from the db to the `../bank_app/db/../authentication` dir.
- [ ] Add any environment variable to the `../bank_app/core/config.py` file.
