### ISSUE TITLE
Create endpoint for viewing all customers profiles

### ISSUE THREAD

**Issue by KennedyUC** [awsnigeriadevops/bank-server#18]
Create an endpoint to get all customers profile

**Comment by KennedyUC** [comment]
## User Story
All customer profiles should be able to be retrieved

## Tasks
- [ ] Implement an endpoint to handle the API requests to the `../bank_app/servers/authentication` dir.
- [ ] Implement the queries and logic to get the records from the db to the `../bank_app/db/../authentication` dir.
- [ ] Add any environment variable to the `../bank_app/core/config.py` file.
