### ISSUE TITLE
Create endpoint for viewing customer profile by email

### ISSUE THREAD

**Issue by KennedyUC** [awsnigeriadevops/bank-server#19]
Create an endpoint to get customer's profile by email

**Comment by KennedyUC** [comment]
## User Story
Should be possible to retrieve a customer's profile using the email

## Tasks
- [ ] Implement an endpoint to handle the API requests to the `../bank_app/servers/authentication` dir.
- [ ] Implement the queries and logic to get the records from the db to the `../bank_app/db/../authentication` dir.
- [ ] Add any environment variable to the `../bank_app/core/config.py` file.
