### ISSUE TITLE
Create endpoint for updating customer profile

### ISSUE THREAD

**Issue by KennedyUC** [awsnigeriadevops/bank-server#20]
Create an endpoint for updating a customer's profile

**Comment by KennedyUC** [comment]
## User Story
The admin should be able to update each customer's profile, based on request.

## Details to update
- address
- email
- phone number

## Tasks
- [ ] Implement an endpoint to handle the API requests to the `../bank_app/servers/authentication` dir.
- [ ] Implement the queries and logic to update the records in the db to the `../bank_app/db/../authentication` dir.
- [ ] Add any environment variable to the `../bank_app/core/config.py` file.
