### ISSUE TITLE
Create endpoint for deleting a customer

### ISSUE THREAD

**Issue by KennedyUC** [awsnigeriadevops/bank-server#21]
Create an endpoint for deleting a customer's profile

**Comment by KennedyUC** [comment]
## User Story
The admin should be able to delete the record of a customer who requests for his/her account to be closed.

## Tasks
- [ ] Implement an endpoint to handle the API requests to the `../bank_app/servers/authentication` dir.
- [ ] Implement the queries and logic to delete the records from the db to the `../bank_app/db/../authentication` dir.
- [ ] Add any environment variable to the `../bank_app/core/config.py` file.
