### ISSUE TITLE
Implement Token-based Authentication

### ISSUE THREAD

**Issue by KennedyUC** [awsnigeriadevops/bank-server#3]
Implement token-based authentication for user login

**Comment by KennedyUC** [comment]
## Tasks
- [ ] Generate JWT (JSON Web Tokens) upon successful login.
- [ ] Validate JWT for subsequent requests to authenticate users.
- [ ] Implement token refresh mechanism for expired tokens.
